# default l0 — use l0dbg for verbose dracut/Kiwi serial logs
default l0
timeout 30

label l0
    kernel /Image
    initrd /initrd
    append plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G console=ttyAML0,115200n8 console=tty0 root=UUID=90ed4cca-7c2e-4ec2-9fa4-4046c27f42ad rootflags=subvol=@ rootdelay=5 DEVICE_TIMEOUT=120 selinux=0 enforcing=0

label l0dbg
    kernel /Image
    initrd /initrd
    append plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G console=ttyAML0,115200n8 console=tty0 root=UUID=90ed4cca-7c2e-4ec2-9fa4-4046c27f42ad rootflags=subvol=@ rootdelay=5 DEVICE_TIMEOUT=120 selinux=0 enforcing=0 rd.debug rd.udev.debug loglevel=7 rd.shell rd.kiwi.debug
