# Use "default l0dbg" while debugging HC4 initrd / dracut on serial (ttyAML0).
default l0
timeout 30

label l0
    kernel /Image
    initrd /initrd
    append security=selinux selinux=1 plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G console=ttyAML0,115200n8 console=tty0 root=UUID=90ed4cca-7c2e-4ec2-9fa4-4046c27f42ad

label l0dbg
    kernel /Image
    initrd /initrd
    append security=selinux selinux=1 plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G console=ttyAML0,115200n8 console=tty0 root=UUID=90ed4cca-7c2e-4ec2-9fa4-4046c27f42ad rd.debug rd.udev.debug loglevel=7 rd.shell rd.kiwi.debug
