# default l0 — use l0dbg for verbose dracut/Kiwi serial logs
default l0
timeout 30

label l0
    fdt /odroid-hc4.dtb
    kernel /Image
    initrd /initrd
    append plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G rd.kiwi.oem.luks.reencrypt rd.neednet=1 console=ttyAML0,115200n8 console=tty0 rd.driver.pre=mmc_core rd.driver.pre=meson_gx_mmc rd.driver.pre=mmc_block root=LABEL=ROOT rootflags=subvol=@/.snapshots/1/snapshot rootdelay=10 rootwait selinux=0 enforcing=0

label l0dbg
    fdt /odroid-hc4.dtb
    kernel /Image
    initrd /initrd
    append plymouth.enable=0 rd.kiwi.oem.maxdisk=5000G rd.kiwi.oem.luks.reencrypt rd.neednet=1 console=ttyAML0,115200n8 console=tty0 rd.driver.pre=mmc_core rd.driver.pre=meson_gx_mmc rd.driver.pre=mmc_block root=LABEL=ROOT rootflags=subvol=@/.snapshots/1/snapshot rootdelay=10 rootwait selinux=0 enforcing=0 rd.debug rd.udev.debug loglevel=7 rd.shell rd.kiwi.debug
